### Health
GET http://127.0.0.1:8000/health

### Create a secret page
POST http://127.0.0.1:8000/secrets
Content-Type: application/json

{
    "secret_message": "meet me at noon by the fountain",
    "font_style": "serif",
    "gif_url": "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExam8xdWhpbW5qMThtamt1bTNpeDgwcjRoNXFhMDIxMDE3dHRnaXdwdSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/f5ehe7RcZPIuFllGOi/giphy.gif",
    "background_colour": "#123456",
    "secret_prompt": "What was our first dog's name?",
    "secret_password": "correct-horse"
}
