"""rename secret_pages to secrets

Revision ID: ac2467f9f4f2
Revises: 10ec332cab8a
Create Date: 2026-08-12 16:54:18.888077

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac2467f9f4f2"
down_revision: str | Sequence[str] | None = "10ec332cab8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secrets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("secret_prompt", sa.String(), nullable=False),
        sa.Column("secret_password_hash", sa.String(length=60), nullable=False),
        sa.Column("secret_encrypted", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("secret_pages")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secret_pages",
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("owner_id", sa.INTEGER(), nullable=True),
        sa.Column("secret_message_prompt", sa.VARCHAR(), nullable=False),
        sa.Column(
            "secret_message_password_hash", sa.VARCHAR(length=60), nullable=False
        ),
        sa.Column("secret_message_info_encrypted", sa.TEXT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("secrets")
    # ### end Alembic commands ###
